import type { Metadata } from "next";
import {Roboto_Flex } from "next/font/google";
import "./globals.css";

const roboto_flex = Roboto_Flex({
  variable: "--font-roboto-flex",
  subsets: ["latin"],
  display: "swap",
  axes:["wdth","slnt","opsz"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto_flex.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
